config/routes.rb
Rails.application.routes.draw do  
resources :projects do    
  resources :tasks
  member do
    get 'invite_users',:as=>"invite_users"
    post "create_invite_users"
  end    
end

devise_for :users 

devise_scope :user do
  root to: "devise/sessions#new"
end

end

app/models/picture.rb
class Picture < ActiveRecord::Base
	belongs_to :imageable, polymorphic: true
	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tasks,:dependent=>:destroy
  has_and_belongs_to_many :users
  belongs_to :user, :foreign_key => 'admin_id'
  has_attached_file :picture, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\Z/

  validates :name,presence: :true,uniqueness: true
  validates :submission_date,presence: :true
  validates :description,presence: :true
  validates :picture,presence: :true
  validate :validate_date, :on => [:create,:update]

private
	def validate_date
	if self.submission_date.present? && self.submission_date < Date.today
		p errors.add :submission_date, "should not be less than today's Date"
	end
end

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  validates :title,presence: :true,uniqueness: true
  validates :description,presence: :true
  validates :due_date,presence: :true
end

app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  has_and_belongs_to_many :projects
  has_attached_file :profile_picture, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :profile_picture, content_type: /\Aimage\/.*\Z/
  devise :database_authenticatable, :registerable,
       :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable

       validates :name,presence: :true
       validates :dob,presence: :true
       validates :company_name,presence: :true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_devise_permitted_parameters, if: :devise_controller?

   protect_from_forgery

 def after_sign_in_path_for(resource)
    # request.env['omniauth.origin'] || stored_location_for(resource) || root_path
    "/projects"
 end


  protected

  def configure_devise_permitted_parameters
    permitted_params = [:email, :password, :password_confirmation, :name,:dob,:company_name,:profile_picture]

    if params[:action] == 'update'
      devise_parameter_sanitizer.for(:account_update) { 
        |u| u.permit(permitted_params << :current_password)
      }
    elsif params[:action] == 'create'
      devise_parameter_sanitizer.for(:sign_up) { 
        |u| u.permit(permitted_params) 
      }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController	
  layout 'application' 
  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  layout 'admin_lte_2'
  before_action :authenticate_user!
  before_action :set_project, only: [:show, :edit, :update, :destroy,:invite_users,:create_invite_users]

  # GET /projects
  # GET /projects.json
  def index    
    @projects = current_user.projects
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @task= Task.new
    @tasks= @project.tasks
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @project.admin_id= current_user.id
    respond_to do |format|
      if @project.save
        current_user.projects << @project
        format.html { redirect_to projects_path, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def invite_users
    p @users= User.where.not(:id=>@project.users.pluck(:id))
  end

  def create_invite_users
     invite_user= User.find_by_id(params[:user])
     @project.users << invite_user
   p UserMailer.invitation_to_user(@project.user,invite_user,@project).deliver
     redirect_to project_path(@project), notice: "Invitation mail was successfully delivered to #{invite_user.email}" 
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :submission_date,:admin_id,:description,:picture)
    end
end

app/controllers/registrations_controller212.rb
# class RegistrationsController < ApplicationController

#   before_filter :configure_permitted_parameters, :only => [:create]

#   protected

#     def configure_permitted_parameters
#       devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name,:dob,:company_name, :email, :password) }
#     end
# end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  layout 'admin_lte_2'
  before_action :authenticate_user!
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show

  end

  # GET /tasks/new
  def new
    @project= Project.find_by_id(params[:project_id])
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit    
    @task = Task.find_by_id(params[:id])
    @project= @task.project
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @project= Project.find_by_id(params[:project_id])
    @task = @project.tasks.build(task_params)
   p @status= @task.save
    @tasks= @project.tasks  
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    @status= @task.update(task_params)
    @project= @task.project
    @tasks= @project.tasks
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @project= @task.project
    @task.destroy
    respond_to do |format|
      format.html { redirect_to project_path(@project), notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :description, :due_date, :project_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/home/index.html.erb
<br>
<% if user_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path)  %>  
  </li>
<% end %>

<% if user_signed_in? %>
  <li>
  <%= link_to('Edit registration', edit_user_registration_path) %>
  </li>
<% else %>
  <li>
  <%= link_to('Register', new_user_registration_path)  %>
  </li>
<% end %>

app/views/layouts/_admin_lte_2_header.html.erb
<!-- Main Header -->
<header class="main-header">

  <!-- Logo -->
  <a href="/" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini"><b>TMS</b></span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><b>TMS</b></span>
  </a>

  <!-- Header Navbar -->
  <nav class="navbar navbar-static-top" role="navigation">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>
    <!-- Navbar Right Menu -->
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <!-- Messages: style can be found in dropdown.less-->
        <li class="dropdown messages-menu">
          <!-- Menu toggle button -->
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-envelope-o"></i>
            <span class="label label-success">4</span>
          </a>
          <ul class="dropdown-menu">
            <li class="header">You have 4 messages</li>
            <li>
              <!-- inner menu: contains the messages -->
              <ul class="menu">
                <li><!-- start message -->
                  <a href="#">
                    <div class="pull-left">
                      <!-- User Image -->
                      <img src="/assets/user2-160x160.jpg" class="img-circle" alt="User Image"/>
                    </div>
                    <!-- Message title and timestamp -->
                    <h4>
                      Support Team
                      <small><i class="fa fa-clock-o"></i> 5 mins</small>
                    </h4>
                    <!-- The message -->
                    <p>Why not buy a new awesome theme?</p>
                  </a>
                </li><!-- end message -->
              </ul><!-- /.menu -->
            </li>
            <li class="footer"><a href="#">See All Messages</a></li>
          </ul>
        </li><!-- /.messages-menu -->

        <!-- Notifications Menu -->
        <li class="dropdown notifications-menu">
          <!-- Menu toggle button -->
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-bell-o"></i>
            <span class="label label-warning">10</span>
          </a>
          <ul class="dropdown-menu">
            <li class="header">You have 10 notifications</li>
            <li>
              <!-- Inner Menu: contains the notifications -->
              <ul class="menu">
                <li><!-- start notification -->
                  <a href="#">
                    <i class="fa fa-users text-aqua"></i> 5 new members joined today
                  </a>
                </li><!-- end notification -->
              </ul>
            </li>
            <li class="footer"><a href="#">View all</a></li>
          </ul>
        </li>
        <!-- Tasks Menu -->
        <li class="dropdown tasks-menu">
          <!-- Menu Toggle Button -->
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-flag-o"></i>
            <span class="label label-danger">9</span>
          </a>
          <ul class="dropdown-menu">
            <li class="header">You have 9 tasks</li>
            <li>
              <!-- Inner menu: contains the tasks -->
              <ul class="menu">
                <li><!-- Task item -->
                  <a href="#">
                    <!-- Task title and progress text -->
                    <h3>
                      Design some buttons
                      <small class="pull-right">20%</small>
                    </h3>
                    <!-- The progress bar -->
                    <div class="progress xs">
                      <!-- Change the css width attribute to simulate progress -->
                      <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                        <span class="sr-only">20% Complete</span>
                      </div>
                    </div>
                  </a>
                </li><!-- end task item -->
              </ul>
            </li>
            <li class="footer">
              <a href="#">View all tasks</a>
            </li>
          </ul>
        </li>
        <!-- User Account Menu -->
        <li class="dropdown user user-menu">
          <!-- Menu Toggle Button -->
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <!-- The user image in the navbar-->
            <img src="<%= current_user.profile_picture.url%>" class="user-image" alt="User Image"/>

            <!-- hidden-xs hides the username on small devices so only the image appears. -->
            <span class="hidden-xs"><%= current_user.name.upcase%></span>
          </a>
          <ul class="dropdown-menu">
            <!-- The user image in the menu -->
            <li class="user-header">
              <img src="/assets/user2-160x160.jpg" class="img-circle" alt="User Image" />
              <p>
                Alexander Pierce - Web Developer
                <small>Member since Nov. 2012</small>
              </p>
            </li>
            <!-- Menu Body -->
            <li class="user-body">
              <div class="col-xs-4 text-center">
                <a href="#">Followers</a>
              </div>
              <div class="col-xs-4 text-center">
                <a href="#">Sales</a>
              </div>
              <div class="col-xs-4 text-center">
                <a href="#">Friends</a>
              </div>
            </li>
            <!-- Menu Footer-->
            <li class="user-footer">
              <div class="pull-left">
                <a href="#" class="btn btn-default btn-flat">Profile</a>
              </div>
              <div class="pull-right">
                <a href="#" class="btn btn-default btn-flat">Sign out</a>
              </div>
            </li>
          </ul>
        </li>
        <li>          
          <%= link_to( destroy_user_session_path, :method => :delete) do%>
            <i class="fa fa-sign-out"></i>
          <%end%>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/_admin_lte_2_sidebar.html.erb
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">

  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">

    <!-- Sidebar user panel (optional) -->
    <div class="user-panel">
      <div class="pull-left image">
        <img src="<%= current_user.profile_picture.url%>" class="img-circle" alt="User Image" />
      </div>
      <div class="pull-left info">
        <p><%= current_user.name.upcase%></p>
        <!-- Status -->
        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
      </div>
    </div>

    <!-- search form (Optional) -->
    <form action="#" method="get" class="sidebar-form">
      <div class="input-group">
        <input type="text" name="q" class="form-control" placeholder="Search..."/>
        <span class="input-group-btn">
          <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
        </span>
      </div>
    </form>
    <!-- /.search form -->

    <!-- Sidebar Menu -->
    <ul class="sidebar-menu">
      <li class="header">HEADER</li>
        <!-- Optionally, you can add icons to the links -->
      <li class="active"><a href="<%= projects_path %>"><i class='fa fa-dashboard'></i> <span>Dashboard</span></a></li>
      <li><a href="<%= new_project_path %>"><i class='fa fa fa-plus'></i> <span>New Project</span></a></li>
     

    </ul><!-- /.sidebar-menu -->
  </section>
  <!-- /.sidebar -->
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TMS</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="skin-blue sidebar-mini fixed <%= params[:controller].parameterize %> <%= action_name %>">
  <div class="wrapper">

    <!-- Main Header -->
<header class="main-header">

  <a href="/" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><b></b>TMS</span>
  </a>

  <!-- Header Navbar -->
  <nav class="navbar navbar-static-top" role="navigation">
    <!-- Sidebar toggle button-->
    
    <!-- Navbar Right Menu -->
    <div class="navbar-custom-menu">
    
    <a href="<%= new_user_registration_path%>" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><b></b>Sign Up</span>
  </a>
    </div></nav></header></div>
<br>
<br>
<br>
<br>
 
<%if alert.present?%>
 <div class = "alert alert-danger"><%= alert %></div>
 <%end%>
<%= yield %>

</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TMS</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

 <%if notice.present?%>
 <div class = "alert alert-success"><%= notice %></div>
 <%end%>

<%if alert.present?%>
 <div class = "alert alert-danger"><%= alert %></div>
 <%end%>
<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<div class="container">    
<div id="loginbox" style="margin-top:50px;" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">                    
<div class="panel panel-info" >
<div class="panel-heading">
<div class="panel-title">Add Project</div>

</div>     

<div style="padding-top:30px" class="panel-body" >

<div style="display:none" id="login-alert" class="alert alert-danger col-sm-12"></div>


<%= simple_form_for(@project) do |f| %> 
<%= f.error_notification %>     
<div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :submission_date %>
    <%= f.input :description %>
    <%= f.input :picture %>
</div>

  <div  class="form-group">        
      <div class="col-sm-12 controls text-center">          
        <%= f.button :submit, "Log in", :class=>"btn btn-primary"%>
      </div>
  </div>

<%end%>  

</div>                     
</div>  
</div>

</div>

app/views/projects/_invite_users.html.erb
<%unless @users.blank?%>
<%= form_tag create_invite_users_project_path(@project) do |f| %>
	<%= select_tag "user", options_from_collection_for_select(@users, "id", "name"),:prompt=>"User Name",:required=>true %>
	<%= submit_tag%>
<%end%>
<%else%>
<h2>No users present.</h2>
<%end%>

app/views/projects/_view_tasks.html.erb
   <div class = "panel-heading" style="height:60px;">
      <h3 class = "panel-title">Tasks
    <div class="pull-right" id="add_task_btn">    
      <%= link_to "Add Task",new_project_task_path(@project),:remote=>true,:class => "btn btn-primary btn-md"%>
    </div>
      </h3>
     
   </div>
   
   <div class = "panel-body">      

        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="pull-right"> <a id="expandAll" href="#" class="btn btn-default" role="button">Expand All</a>

                <a id="collapseAll" href="#" class="btn btn-default" role="button">Collapse All</a>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" >
            <div class="panel-group" id="accordion">

            <%unless @tasks.blank?%>

<%@tasks.each_with_index do |task,i|%>
<div class="panel panel-default">
    <div class="panel-heading">
         <h4 class="panel-title">
              <a data-toggle="collapse" data-parent="#accordion" href="#collapse<%= i.to_s%>" class="">
                <%= task.title%>
              </a>
          
            </h4>

    </div>
    <div id="collapse<%= i.to_s%>" class="panel-collapse collapse">
        <div class="panel-body"><%= task.description%></div>
    </div>
</div>
<%end%>

<%else%>
 <h4>No tasks present.</h4>
<%end%> 
                
            </div>
        </div>
 

   </div>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h3 class="text-center" >Listing Projects</h3>


<div class="container-fluid">
<div class = "row"  >
<%if @projects.present?%>
    <% @projects.each do |project| %>
   <div class = "col-sm-6 col-md-3" style="margin-top:15px;">
      <div  style="height:200px;">
         <%= image_tag(project.picture.url,:size=>"200x250") %>
      </div>
      
      <div class = "caption">
      <br><br>
         <h3><%= link_to project.name, project,:style=>"text-decoration: none;background-color:transparent;"%></h3>
         <p><%= project.description %></p>
         
         <p>
            
            <%= link_to 'Show', project,:class => "btn btn-primary" ,:style=>"color:white;"%>
            <%unless project.admin_id != current_user.id%>
            <%= link_to 'Edit', edit_project_path(project),:class => "btn btn-primary" ,:style=>"color:white;" %>
            <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } ,:class => "btn btn-primary" ,:style=>"color:white;"%>
            <%else%>
              <p>Created by <%= project.user.name%> on <%= project.created_at.strftime("%d-%m-%Y")%>.</p>
            <%end%>
          
         </p>
         
      </div>
   </div>
   <%end%>
   <%else%>
      <h4 class="text-center">No projects to display.</h4>
   <%end%>


   </div>
</div>
<br>

app/views/projects/invite_users.js.erb
$('#myModal').modal('show');
$('.modal-body').html('<%= j (render 'invite_users') %>');

app/views/projects/new.html.erb
<h3 class="text-center">New Project</h3>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<div><%= @project.name.upcase%><%= link_to "Invite User",invite_users_project_path(@project),:remote=>true,:class => "btn btn-primary btn-md pull-right"%></div>
<div class="clearfix"></div><br>
<div class = "panel panel-info" id="taskDiv">

   <%= render 'view_tasks'%>
</div>


<%= link_to 'Back', projects_path %>


<script type="text/javascript">
	$(function () {			
                    $('a[data-toggle="collapse"]').on('click',function(){
				
				var objectID=$(this).attr('href');
				
				if($(objectID).hasClass('in'))
				{
                                    $(objectID).collapse('hide');
				}
				
				else{
                                    $(objectID).collapse('show');
				}
                    });
                    
                    
                    $('#expandAll').on('click',function(){
                        
                        $('a[data-toggle="collapse"]').each(function(){
                            var objectID=$(this).attr('href');
                            if($(objectID).hasClass('in')===false)
                            {
                                 $(objectID).collapse('show');
                            }
                        });
                    });
                    
                    $('#collapseAll').on('click',function(){
                        
                        $('a[data-toggle="collapse"]').each(function(){
                            var objectID=$(this).attr('href');
                            $(objectID).collapse('hide');
                        });
                    });
                    
		});
</script>

<style type="text/css">
	/* CSS used here will be applied after bootstrap.css */
.col-xs-12,.col-sm-12,.col-md-12,.col-lg-12{margin-bottom: 20px;}
</style>




<!-- Modal -->
<div class = "modal fade" id = "myModal" tabindex = "-1" role = "dialog" 
   aria-labelledby = "myModalLabel" aria-hidden = "true">
   
   <div class = "modal-dialog">
      <div class = "modal-content">
         
         <div class = "modal-header">
            <button type = "button" class = "close" data-dismiss = "modal" aria-hidden = "true">
                  &times;
            </button>
            
            <h4 class = "modal-title" id = "myModalLabel">
               
            </h4>
         </div>
         
         <div class = "modal-body">
           
         </div>
         
         
         
      </div><!-- /.modal-content -->
   </div><!-- /.modal-dialog -->
  
</div><!-- /.modal -->

app/views/tasks/_form.html.erb
<%= simple_form_for [@project,@task],:remote=>true do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :due_date %>    
  </div>

  <div class = "modal-footer">
    <button type = "button" class = "btn btn-default" data-dismiss = "modal">
       Close
    </button>
       <%= f.button :submit,:class => "btn btn-primary" %>
  </div>
<% end %>

app/views/tasks/create.js.erb
<%if @status == true%>
	// $('#myModal').hide();
	// $('#taskDiv').html("");
	// $('#taskDiv').html('<%= j (render 'projects/view_tasks') %>');
	window.location.href = "<%= j project_path(@project) %>";
<%else%>
	$('#myModal').modal('show');
	$('.modal-body').html('<%= j (render 'tasks/form') %>');
<%end%>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/edit.js.erb
$('#myModal').modal('show');
$('.modal-body').html('<%= j (render 'tasks/form') %>');

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Due date</th>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.description %></td>
        <td><%= task.due_date %></td>
        <td><%= task.project %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

app/views/tasks/new.js.erb
$('#myModal').modal('show');
$('.modal-body').html('<%= j (render 'tasks/form') %>');

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @task.due_date %>
</p>

<p>
  <strong>Project:</strong>
  <%= @task.project %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/update.js.erb
<%if @status == true%>
	window.location.href = "<%= j project_path(@project) %>";
<%else%>
	$('#myModal').modal('show');
	$('.modal-body').html('<%= j (render 'tasks/form') %>');
<%end%>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>